# Generated by Django 2.2 on 2018-01-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='shortened_url',
            field=models.CharField(max_length=6, verbose_name='Shortened Url'),
        ),
    ]
